### ISSUE TITLE
sparkbench.inputformat & sparkbench.outputformat

### ISSUE THREAD

**Issue by panfengfeng** [intel-hadoop/HiBench#105]
when some workloads generate data, they appoint the output format—— “-o sequence”, like bayes, SQL and so on, does it mean that  i should change the sparkbench.inputformat and sparkbench.outputformat in 00-default-properties.conf since the defalut are "Text" ?

**Comment by lvsoft** [comment]
No. 

Actually, current release did not fully integrate input/output format configurations yet due to the limitation of `autogen` module (which'll generate data samples). So basically, set `sparkbench.outputformat` will have no effects now. They are just prepared for future works.

However, `sparkbench.inputformat` will take effects on some spark related workloads(wordcount, sort, ...),  while data generator of wordcount and sort (RandomTextWriter of hadoop-example, actually) will only generate "Text" format, so the configurations must  be set to "Text" currently.

In a word, I'll not suggest to modify input/output format related configurations. However, if you are interested, it's always welcomed to refine the data generator and configuration script for a better support of input/output format.

**Comment by pzhanggit** [comment]
Hi @lvsoft, does the current release support `sparkbench.inputformat ` and `sparkbench.outputformat` both be `Text` in thewordcount example?  The default values are "Sequence". After I switched them to "Text", the output file of wordcount is in "Text" format, but the data generated from RandomTextWriter still seems to be in "Sequence", as in

> SEQorg.apache.hadoop.io.Textorg.apache.hadoop.io.Texta��ńv$n�u�R�m@��VUhondo hogmace engrain misexposition epauliere arrowworm perfunctory gorilloid tetchy �farrendation knob skyshine mastication predebit unrealize naprapath orthopedical gelatinousness depthwise floatability unstipulated hypochondriacism mechanist neuromimesis ten frameable electrotechnics rizzomed hymnic putative serpentinic debellator pentafid cattimandoo waird uncontradictableness cattimandoo goodwill opacousness bespin placatory airfreighter arduousness mammonish tristich uncarefully Auriculariales corelysis antivenin counterappellant debellator proboscidiform seminonflammable Dawsonia depravity incalculable classificational flippantness dastardliness imperceptivity frictionlessly untongued
